## => Site Settings
##############################
text_skin: default # "default" (default), "dark", "forest", "ocean", "chocolate", "orange"
highlight_theme: tomorrow-night # "default" (default), "tomorrow", "tomorrow-night", "tomorrow-night-eighties", "tomorrow-night-blue", "tomorrow-night-bright"
url     : https://erowz.github.io # the base hostname & protocol for your site e.g. https://www.someone.com
baseurl : # does not include hostname
title   : La blogo de "Y Kaj Nai"
description: > # this means to ignore newlines until "Language & timezone"
  嚴與渿的博客 | Blog


## => Language and Timezone
##############################
lang: # the language of your site, default as "en"
timezone:	Asia/Shanghai # see https://en.데이터 싸이언티스트와 데이터 애널리스트, 데이터 엔지니어, 비즈니스 애널리스트wikipedia.org/wiki/List_of_tz_database_time_zones for the available values


## => Author and Social
##############################
author:
  type      : # "person" (default), "organization"
  name      : Erowz
  url       :
  avatar    : # path or url of avatar image (square)
  bio       : 嚴與渿的博客 | Blog
  email     :
  facebook  : # "user_name" the last part of your profile url, e.g. https://www.facebook.com/user_name
  twitter   : # "user_name" the last part of your profile url, e.g. https://twitter.com/user_name
  weibo     : # "user_id"   the last part of your profile url, e.g. https://www.weibo.com/user_id/profile?...
  googleplus: # "user_id"   the last part of your profile url, e.g. https://plus.google.com/u/0/user_id
  telegram  : erowz # "user_name" the last part of your profile url, e.g. https://t.me/user_name
  medium    : # "user_name" the last part of your profile url, e.g. https://medium.com/user_name
  zhihu     : wassup-57 # "user_name" the last part of your profile url, e.g. https://www.zhihu.com/people/user_name
  douban    : # "user_name" the last part of your profile url, e.g. https://www.douban.com/people/user_name
  linkedin  : # "user_name" the last part of your profile url, e.g. https://www.linkedin.com/in/user_name
  github    : erowz # "user_name" the last part of your profile url, e.g. https://github.com/user_name
  npm       : # "user_name" the last part of your profile url, e.g. https://www.npmjs.com/~user_name

## => GitHub Repository (if the site is hosted by GitHub)
##############################
repository: erowz
repository_tree: master


## => Paths
##############################
paths:
  root    : # title link url, "/" (default)
  home    : # home layout url, "/" (default)
  archive : # "/archive.html" (default)
  rss     : # "/feed.xml" (default)


## => Post
##############################
## excerpt
excerpt_separator: <!--more-->

## license
## license: CC-BY-ND-4.0 # "CC-BY-4.0", "CC-BY-SA-4.0", "CC-BY-NC-4.0", "CC-BY-ND-4.0"

## TOC
toc:
  selectors: # "h1,h2,h3" (default)


## => Markdown Enhancements
##############################
## Mathjax
mathjax: true # false (default), true
mathjax_autoNumber: # false (default), true

## Mermaid
mermaid: true # false (default), true

## Chart
chart: true # false (default), true


## => Paginate
##############################
paginate: 10
paginate_path: /page:num # don't change this unless for special need


## => Sources
##############################
sources: # bootcdn (default), unpkg


## => Sharing
##############################
sharing:
  provider: addthis # false (default), "addtoany", "addthis", "custom"

  ## AddThis
  addthis:
    id: ra-5f1c0ffa0adb6f6a # AddThis pubid, e.g. ra-5xxxxxxxxxxx


## => Comments
##############################
comments:
  provider: false # false (default), "disqus", "gitalk", "valine", "custom"

  ## Disqus
  disqus:
    shortname: # the Disqus shortname for the site

  ## Gitalk
  # please refer to https://github.com/gitalk/gitalk for more info.
  gitalk:
    clientID    : # GitHub Application Client ID
    clientSecret: # GitHub Application Client Secret
    repository  : # GitHub repo
    owner       : # GitHub repo owner
    admin: # GitHub repo owner and collaborators, only these guys can initialize GitHub issues, IT IS A LIST.
      # - your GitHub Id

  ## Valine
  # please refer to https://valine.js.org/en/ for more info.
  valine:
    app_id      : 7hgyMrKUuyLB2dXPeeia9O72-gzGzoHsz # LeanCloud App id
    app_key     : bSWXyG6X950FhYGplIvUhvKb # LeanCloud App key
    placeholder : 点击评论，记得输入上方的昵称喔~ # Prompt information
    emojiCDN: //erowz.github.io/img/bqb/
        emojiMaps: {
        "tv_doge": "6ea59c827c414b4a2955fe79e0f6fd3dcd515e24.png",
        "tv_亲亲": "a8111ad55953ef5e3be3327ef94eb4a39d535d06.png",
        "tv_偷笑": "bb690d4107620f1c15cff29509db529a73aee261.png",
        "tv_再见": "180129b8ea851044ce71caf55cc8ce44bd4a4fc8.png",
        "tv_冷漠": "b9cbc755c2b3ee43be07ca13de84e5b699a3f101.png",
        "tv_发怒": "34ba3cd204d5b05fec70ce08fa9fa0dd612409ff.png",
        "tv_发财": "34db290afd2963723c6eb3c4560667db7253a21a.png",
        "tv_可爱": "9e55fd9b500ac4b96613539f1ce2f9499e314ed9.png",
        "tv_吐血": "09dd16a7aa59b77baa1155d47484409624470c77.png",
        "tv_呆": "fe1179ebaa191569b0d31cecafe7a2cd1c951c9d.png",
        "tv_困": "241ee304e44c0af029adceb294399391e4737ef2.png",
        "tv_大佬": "093c1e2c490161aca397afc45573c877cdead616.png",
        "tv_大哭": "23269aeb35f99daee28dda129676f6e9ea87934f.png",
        "tv_委屈": "d04dba7b5465779e9755d2ab6f0a897b9b33bb77.png",
        "tv_害羞": "a37683fb5642fa3ddfc7f4e5525fd13e42a2bdb1.png",
        "tv_尴尬": "7cfa62dafc59798a3d3fb262d421eeeff166cfa4.png",
        "tv_微笑": "70dc5c7b56f93eb61bddba11e28fb1d18fddcd4c.png",
        "tv_思考": "90cf159733e558137ed20aa04d09964436f618a1.png",
        "tv_惊吓": "0d15c7e2ee58e935adc6a7193ee042388adc22af.png",
        "tv_电视笑": "911f987aa8bc1bee12d52aafe62bc41ef4474e6c.png",
        "ni_疑惑": "7750b698d15a1b8e83c0f59106e8e9cd5cb57897.png",
        "ni_坏笑": "d3717f10ffe9787336bc39a09214270988521a67.png",
        "em_狗头": "bba7c12aa51fed0199c241465560dfc2714c593e.png",
        "em_斜笑": "d15121545a99ac46774f1f4465b895fe2d1411c3.png",
        "em_星星眼": "63c9d1a31c0da745b61cdb35e0ecb28635675db2.png",
        "em_哦呼": "362bded07ea5434886271d23fa25f5d85d8af06c.png",
        "em_害羞": "9d2ec4e1fbd6cb1b4d12d2bbbdd124ccb83ddfda.png",
        "em_大笑": "ca94ad1c7e6dac895eb5b33b7836b634c614d1c0.png",
        "em_认真": "685612eadc33f6bc233776c6241813385844f182.png",
        "em_嘘声": "e64af664d20716e090f10411496998095f62f844.png",
        "em_再见": "fc510306bae26c9aec7e287cdf201ded27b065b9.png",
        "em_吃瓜": "4191ce3c44c2b3df8fd97c33f85d3ab15f4f3c84.png",
        "em_笑哭": "485a7e0c01c2d70707daae53bee4a9e2e31ef1ed.png",
        "em_迷醉": "44667b7d9349957e903b1b62cb91fb9b13720f04.png",
        "em_问号": "b7840db4b1f9f4726b7cb23c0972720c1698d661.png",
        "xr_抱抱": "41780a4254750cdaaccb20735730a36044e98ef3.png",
        "xr_跪了": "f2b3aee7e521de7799d4e3aa379b01be032698ac.png",
        "wz_妙啊": "0e98299d7decf5eaffad854977946075c3e91cb8.png",
        "wz_秀": "50782fbf5d9b7f48f9467b5c53932981e321eedc.png",
        "wz_都要": "d424d1ad8d14c1c9b8367842bc68c658b9229bc1.png",
        "wz_内味": "7ca61680a905b5b6e2e335c630e725b648b03b4d.png",
        "wz_猛男": "c97064450528a0e45c7e7c365a15fbb13fd61d8c.png",
        "wz_爱了": "2a165b555ba20391316366c664ed7891883dc5aa.png",
        // ... 更多表情
    } 
    visitor     : # false (default)
    meta        : nick # "[nick, mail, link]" (default) nickname, E-mail, Personal-site


## => Pageview
##############################
pageview:
  provider: false # false (default), "leancloud", "custom"

  ## Leancloud
  leancloud:
    app_id    : # LeanCloud App id
    app_key   : # LeanCloud App key
    app_class : # LeanCloud App class


## => Search 
##############################
search:
  provider: default # "default" (default), false, "google", "custom"

  ## Google Custom Search Engine
  google:
    custom_search_engine_id: # Google Custom Search Engine ID


## => Analytics
##############################
analytics:
  provider: # false (default), "google", "custom"

  ## Google Analytics
  google:
    tracking_id : # Google Analytics id for the site
    anonymize_ip:  # Anonymize IP tracking for Analytics

## Google Font
google_fonts : 

## => Build
##############################
markdown    : kramdown
highlighter : rouge
permalink   : /:categories/:title

## => Dev
############################## 
# show_drafts : true

exclude:
  - CHANGELOG.md
  - HOW_TO_RELEASE.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /docs
  - /node_modules
  - /screenshots
  - /test
  - /vendor

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      sharing: true
      license: false
      aside:
        toc: true
      sidebar:
        nav: nav-zh
      show_edit_on_github: false
      show_subscribe: false
      pageview: false
      fullwidth: true
      imgpath: "/assets/images"
  - scope:
      path: "category"
    values:
      layout: category
      sidebar:
        nav: nav-zh


## => Plugins
##############################
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
